
on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup nodejs 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.x'
      - name: cache npm deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-cache
      - name: install deps
        run: npm install

